# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 12:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_post_isfavorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='isFavorite',
            new_name='isUpVoted',
        ),
    ]
