# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0012_remove_post_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='upVoteCounter',
            field=models.IntegerField(default=0),
        ),
    ]
